language: python

install:
  - pip install coveralls tox

env:
  - TOXENV=py26-django16
  - TOXENV=py27-django16
  - TOXENV=py33-django16
  - TOXENV=py27-django17
  - TOXENV=py33-django17
  - TOXENV=py34-django17

script:
  - tox

after_success: coveralls
