language: python

install:
  - pip install coveralls tox

env:
  - TOXENV=py27-django18
  - TOXENV=py33-django18
  - TOXENV=py34-django18
  - TOXENV=py35-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django110
  - TOXENV=py35-django110

script:
  - tox

after_success: coveralls
