[tool.poetry]
name = "django-misaka"
version = "0.2.1"
description = "A Django app for rendering Markdown (by Misaka Markdown parser)."
authors = ["Chieh Tu <me@chiehtu.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
misaka = "~2.1.1"
Pygments = "~2.6.1"

[tool.poetry.dev-dependencies]
coverage = "^5.0.3"
tox = "^3.14.3"
Django = [
    { version = "~3.2.14", python = "^3.7" },
    { version = "~4.0.6", python = "^3.8" },
]
pytest = "^7.1.2"
pytest-django = "^4.5.2"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
