[tox]
isolated_build = True
envlist =
    py{310,311,312}-django42
    py{310,311,312,313}-django51
    py{310,311,312,313}-django52
    report
    clean

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[coverage:run]
branch = True
parallel = True

[testenv]
deps =
    coverage >= 7.6.1, < 8.0.0
    pytest >= 8.3.2, < 9.0.0
    pytest-django >= 4.5.2, < 5.0.0
    django42: Django >= 4.2.15, == 4.2.*
    django51: Django >= 5.1, == 5.1.*
    django52: Django >= 5.2, == 5.2.*
commands =
    coverage run --parallel --source=. --module pytest

[testenv:report]
deps = coverage
skip_install = true
allowlist_externals = /bin/bash
depends =
    py{310,311,312}-django42
    py{310,311,312,313}-django51
    py{310,311,312,313}-django52
commands =
    coverage combine
    coverage report --skip-covered --show-missing
    coverage lcov

[testenv:clean]
deps = coverage
skip_install = true
depends =
    report
commands =
    coverage erase
